channels:
- conda-forge
dependencies:
- python=3.12.8
- pip<=24.2
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.3
  - psutil==5.9.0
  - pyyaml==6.0.2
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
